import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;

client.Account accountToClient(server.Account account) => client.Account(
      id: account.fhirId,
      meta: account.meta,
      implicitRules: account.implicitRules,
      implicitRulesElement: account.implicitRulesElement,
      language: account.language,
      languageElement: account.languageElement,
      text: account.text,
      contained: account.contained,
      extension_: account.extension_,
      modifierExtension: account.modifierExtension,
      identifier: account.identifier,
      status: account.status,
      statusElement: account.statusElement,
      billingStatus: account.billingStatus,
      type: account.type,
      name: account.name,
      nameElement: account.nameElement,
      subject: account.subject,
      servicePeriod: account.servicePeriod,
      coverage: account.coverage,
      owner: account.owner,
      description: account.description,
      descriptionElement: account.descriptionElement,
      guarantor: account.guarantor,
      diagnosis: account.diagnosis,
      procedure: account.procedure,
      relatedAccount: account.relatedAccount,
      currency: account.currency,
      balance: account.balance,
      calculatedAt: account.calculatedAt,
      calculatedAtElement: account.calculatedAtElement,
    );
