import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.Account accountccountToServer(server.Account resource) => client.Account(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
billingStatus: resource.billingStatus == null ? null : resource.billingStatus,
type: resource.type == null ? null : resource.type,
name: resource.name == null ? null : resource.name,
nameElement: resource.nameElement == null ? null : resource.nameElement,
subject: resource.subject == null ? null : resource.subject,
servicePeriod: resource.servicePeriod == null ? null : resource.servicePeriod,
coverage: resource.coverage == null ? null : resource.coverage,
owner: resource.owner == null ? null : resource.owner,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
guarantor: resource.guarantor == null ? null : resource.guarantor,
diagnosis: resource.diagnosis == null ? null : resource.diagnosis,
procedure: resource.procedure == null ? null : resource.procedure,
relatedAccount: resource.relatedAccount == null ? null : resource.relatedAccount,
currency: resource.currency == null ? null : resource.currency,
balance: resource.balance == null ? null : resource.balance,
calculatedAt: resource.calculatedAt == null ? null : resource.calculatedAt,
calculatedAtElement: resource.calculatedAtElement == null ? null : resource.calculatedAtElement,

);
