import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.AllergyIntolerance allergyintolerancellergyIntoleranceToServer(server.AllergyIntolerance resource) => client.AllergyIntolerance(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
clinicalStatus: resource.clinicalStatus == null ? null : resource.clinicalStatus,
verificationStatus: resource.verificationStatus == null ? null : resource.verificationStatus,
type: resource.type == null ? null : resource.type,
category: resource.category == null ? null : resource.category,
categoryElement: resource.categoryElement == null ? null : resource.categoryElement,
criticality: resource.criticality == null ? null : resource.criticality,
criticalityElement: resource.criticalityElement == null ? null : resource.criticalityElement,
code: resource.code == null ? null : resource.code,
patient: resource.patient == null ? null : resource.patient,
encounter: resource.encounter == null ? null : resource.encounter,
onsetDateTime: resource.onsetDateTime == null ? null : resource.onsetDateTime,
onsetDateTimeElement: resource.onsetDateTimeElement == null ? null : resource.onsetDateTimeElement,
onsetAge: resource.onsetAge == null ? null : resource.onsetAge,
onsetPeriod: resource.onsetPeriod == null ? null : resource.onsetPeriod,
onsetRange: resource.onsetRange == null ? null : resource.onsetRange,
onsetString: resource.onsetString == null ? null : resource.onsetString,
onsetStringElement: resource.onsetStringElement == null ? null : resource.onsetStringElement,
recordedDate: resource.recordedDate == null ? null : resource.recordedDate,
recordedDateElement: resource.recordedDateElement == null ? null : resource.recordedDateElement,
participant: resource.participant == null ? null : resource.participant,
lastOccurrence: resource.lastOccurrence == null ? null : resource.lastOccurrence,
lastOccurrenceElement: resource.lastOccurrenceElement == null ? null : resource.lastOccurrenceElement,
note: resource.note == null ? null : resource.note,
reaction: resource.reaction == null ? null : resource.reaction,

);
