import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.Appointment appointmentppointmentToServer(server.Appointment resource) => client.Appointment(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
cancellationReason: resource.cancellationReason == null ? null : resource.cancellationReason,
class_: resource.class_ == null ? null : resource.class_,
serviceCategory: resource.serviceCategory == null ? null : resource.serviceCategory,
serviceType: resource.serviceType == null ? null : resource.serviceType,
specialty: resource.specialty == null ? null : resource.specialty,
appointmentType: resource.appointmentType == null ? null : resource.appointmentType,
reason: resource.reason == null ? null : resource.reason,
priority: resource.priority == null ? null : resource.priority,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
replaces: resource.replaces == null ? null : resource.replaces,
virtualService: resource.virtualService == null ? null : resource.virtualService,
supportingInformation: resource.supportingInformation == null ? null : resource.supportingInformation,
previousAppointment: resource.previousAppointment == null ? null : resource.previousAppointment,
originatingAppointment: resource.originatingAppointment == null ? null : resource.originatingAppointment,
start: resource.start == null ? null : resource.start,
startElement: resource.startElement == null ? null : resource.startElement,
end: resource.end == null ? null : resource.end,
endElement: resource.endElement == null ? null : resource.endElement,
minutesDuration: resource.minutesDuration == null ? null : resource.minutesDuration,
minutesDurationElement: resource.minutesDurationElement == null ? null : resource.minutesDurationElement,
requestedPeriod: resource.requestedPeriod == null ? null : resource.requestedPeriod,
slot: resource.slot == null ? null : resource.slot,
account: resource.account == null ? null : resource.account,
created: resource.created == null ? null : resource.created,
createdElement: resource.createdElement == null ? null : resource.createdElement,
cancellationDate: resource.cancellationDate == null ? null : resource.cancellationDate,
cancellationDateElement: resource.cancellationDateElement == null ? null : resource.cancellationDateElement,
note: resource.note == null ? null : resource.note,
patientInstruction: resource.patientInstruction == null ? null : resource.patientInstruction,
basedOn: resource.basedOn == null ? null : resource.basedOn,
subject: resource.subject == null ? null : resource.subject,
participant: resource.participant == null ? null : resource.participant,
recurrenceId: resource.recurrenceId == null ? null : resource.recurrenceId,
recurrenceIdElement: resource.recurrenceIdElement == null ? null : resource.recurrenceIdElement,
occurrenceChanged: resource.occurrenceChanged == null ? null : resource.occurrenceChanged,
occurrenceChangedElement: resource.occurrenceChangedElement == null ? null : resource.occurrenceChangedElement,
recurrenceTemplate: resource.recurrenceTemplate == null ? null : resource.recurrenceTemplate,

);
