import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ArtifactAssessment artifactassessmentrtifactAssessmentToServer(server.ArtifactAssessment resource) => client.ArtifactAssessment(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
title: resource.title == null ? null : resource.title,
titleElement: resource.titleElement == null ? null : resource.titleElement,
citeAsReference: resource.citeAsReference == null ? null : resource.citeAsReference,
citeAsMarkdown: resource.citeAsMarkdown == null ? null : resource.citeAsMarkdown,
citeAsMarkdownElement: resource.citeAsMarkdownElement == null ? null : resource.citeAsMarkdownElement,
date: resource.date == null ? null : resource.date,
dateElement: resource.dateElement == null ? null : resource.dateElement,
copyright: resource.copyright == null ? null : resource.copyright,
copyrightElement: resource.copyrightElement == null ? null : resource.copyrightElement,
approvalDate: resource.approvalDate == null ? null : resource.approvalDate,
approvalDateElement: resource.approvalDateElement == null ? null : resource.approvalDateElement,
lastReviewDate: resource.lastReviewDate == null ? null : resource.lastReviewDate,
lastReviewDateElement: resource.lastReviewDateElement == null ? null : resource.lastReviewDateElement,
artifactReference: resource.artifactReference == null ? null : resource.artifactReference,
artifactCanonical: resource.artifactCanonical == null ? null : resource.artifactCanonical,
artifactCanonicalElement: resource.artifactCanonicalElement == null ? null : resource.artifactCanonicalElement,
artifactUri: resource.artifactUri == null ? null : resource.artifactUri,
artifactUriElement: resource.artifactUriElement == null ? null : resource.artifactUriElement,
content: resource.content == null ? null : resource.content,
workflowStatus: resource.workflowStatus == null ? null : resource.workflowStatus,
workflowStatusElement: resource.workflowStatusElement == null ? null : resource.workflowStatusElement,
disposition: resource.disposition == null ? null : resource.disposition,
dispositionElement: resource.dispositionElement == null ? null : resource.dispositionElement,

);
