import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.Attachment attachmentttachmentToServer(server.Attachment resource) => client.Attachment(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
contentType: resource.contentType == null ? null : resource.contentType,
contentTypeElement: resource.contentTypeElement == null ? null : resource.contentTypeElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
data: resource.data == null ? null : resource.data,
dataElement: resource.dataElement == null ? null : resource.dataElement,
url: resource.url == null ? null : resource.url,
urlElement: resource.urlElement == null ? null : resource.urlElement,
size: resource.size == null ? null : resource.size,
sizeElement: resource.sizeElement == null ? null : resource.sizeElement,
hash: resource.hash == null ? null : resource.hash,
hashElement: resource.hashElement == null ? null : resource.hashElement,
title: resource.title == null ? null : resource.title,
titleElement: resource.titleElement == null ? null : resource.titleElement,
creation: resource.creation == null ? null : resource.creation,
creationElement: resource.creationElement == null ? null : resource.creationElement,
height: resource.height == null ? null : resource.height,
heightElement: resource.heightElement == null ? null : resource.heightElement,
width: resource.width == null ? null : resource.width,
widthElement: resource.widthElement == null ? null : resource.widthElement,
frames: resource.frames == null ? null : resource.frames,
framesElement: resource.framesElement == null ? null : resource.framesElement,
duration: resource.duration == null ? null : resource.duration,
durationElement: resource.durationElement == null ? null : resource.durationElement,
pages: resource.pages == null ? null : resource.pages,
pagesElement: resource.pagesElement == null ? null : resource.pagesElement,

);
