import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.CapabilityStatementResource capabilitystatementresourceapabilityStatementResourceToServer(server.CapabilityStatementResource resource) => client.CapabilityStatementResource(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
type: resource.type == null ? null : resource.type,
typeElement: resource.typeElement == null ? null : resource.typeElement,
profile: resource.profile == null ? null : resource.profile,
supportedProfile: resource.supportedProfile == null ? null : resource.supportedProfile,
documentation: resource.documentation == null ? null : resource.documentation,
documentationElement: resource.documentationElement == null ? null : resource.documentationElement,
interaction: resource.interaction == null ? null : resource.interaction,
versioning: resource.versioning == null ? null : resource.versioning,
versioningElement: resource.versioningElement == null ? null : resource.versioningElement,
readHistory: resource.readHistory == null ? null : resource.readHistory,
readHistoryElement: resource.readHistoryElement == null ? null : resource.readHistoryElement,
updateCreate: resource.updateCreate == null ? null : resource.updateCreate,
updateCreateElement: resource.updateCreateElement == null ? null : resource.updateCreateElement,
conditionalCreate: resource.conditionalCreate == null ? null : resource.conditionalCreate,
conditionalCreateElement: resource.conditionalCreateElement == null ? null : resource.conditionalCreateElement,
conditionalRead: resource.conditionalRead == null ? null : resource.conditionalRead,
conditionalReadElement: resource.conditionalReadElement == null ? null : resource.conditionalReadElement,
conditionalUpdate: resource.conditionalUpdate == null ? null : resource.conditionalUpdate,
conditionalUpdateElement: resource.conditionalUpdateElement == null ? null : resource.conditionalUpdateElement,
conditionalPatch: resource.conditionalPatch == null ? null : resource.conditionalPatch,
conditionalPatchElement: resource.conditionalPatchElement == null ? null : resource.conditionalPatchElement,
conditionalDelete: resource.conditionalDelete == null ? null : resource.conditionalDelete,
conditionalDeleteElement: resource.conditionalDeleteElement == null ? null : resource.conditionalDeleteElement,
referencePolicy: resource.referencePolicy == null ? null : resource.referencePolicy,
referencePolicyElement: resource.referencePolicyElement == null ? null : resource.referencePolicyElement,
searchInclude: resource.searchInclude == null ? null : resource.searchInclude,
searchIncludeElement: resource.searchIncludeElement == null ? null : resource.searchIncludeElement,
searchRevInclude: resource.searchRevInclude == null ? null : resource.searchRevInclude,
searchRevIncludeElement: resource.searchRevIncludeElement == null ? null : resource.searchRevIncludeElement,
searchParam: resource.searchParam == null ? null : resource.searchParam,
operation: resource.operation == null ? null : resource.operation,

);
