import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.CitationPublicationForm citationpublicationformitationPublicationFormToServer(server.CitationPublicationForm resource) => client.CitationPublicationForm(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
publishedIn: resource.publishedIn == null ? null : resource.publishedIn,
citedMedium: resource.citedMedium == null ? null : resource.citedMedium,
volume: resource.volume == null ? null : resource.volume,
volumeElement: resource.volumeElement == null ? null : resource.volumeElement,
issue: resource.issue == null ? null : resource.issue,
issueElement: resource.issueElement == null ? null : resource.issueElement,
articleDate: resource.articleDate == null ? null : resource.articleDate,
articleDateElement: resource.articleDateElement == null ? null : resource.articleDateElement,
publicationDateText: resource.publicationDateText == null ? null : resource.publicationDateText,
publicationDateTextElement: resource.publicationDateTextElement == null ? null : resource.publicationDateTextElement,
publicationDateSeason: resource.publicationDateSeason == null ? null : resource.publicationDateSeason,
publicationDateSeasonElement: resource.publicationDateSeasonElement == null ? null : resource.publicationDateSeasonElement,
lastRevisionDate: resource.lastRevisionDate == null ? null : resource.lastRevisionDate,
lastRevisionDateElement: resource.lastRevisionDateElement == null ? null : resource.lastRevisionDateElement,
language: resource.language == null ? null : resource.language,
accessionNumber: resource.accessionNumber == null ? null : resource.accessionNumber,
accessionNumberElement: resource.accessionNumberElement == null ? null : resource.accessionNumberElement,
pageString: resource.pageString == null ? null : resource.pageString,
pageStringElement: resource.pageStringElement == null ? null : resource.pageStringElement,
firstPage: resource.firstPage == null ? null : resource.firstPage,
firstPageElement: resource.firstPageElement == null ? null : resource.firstPageElement,
lastPage: resource.lastPage == null ? null : resource.lastPage,
lastPageElement: resource.lastPageElement == null ? null : resource.lastPageElement,
pageCount: resource.pageCount == null ? null : resource.pageCount,
pageCountElement: resource.pageCountElement == null ? null : resource.pageCountElement,
copyright: resource.copyright == null ? null : resource.copyright,
copyrightElement: resource.copyrightElement == null ? null : resource.copyrightElement,

);
