import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ClaimResponse claimresponselaimResponseToServer(server.ClaimResponse resource) => client.ClaimResponse(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
traceNumber: resource.traceNumber == null ? null : resource.traceNumber,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
type: resource.type == null ? null : resource.type,
subType: resource.subType == null ? null : resource.subType,
use: resource.use == null ? null : resource.use,
useElement: resource.useElement == null ? null : resource.useElement,
patient: resource.patient == null ? null : resource.patient,
created: resource.created == null ? null : resource.created,
createdElement: resource.createdElement == null ? null : resource.createdElement,
insurer: resource.insurer == null ? null : resource.insurer,
requestor: resource.requestor == null ? null : resource.requestor,
request: resource.request == null ? null : resource.request,
outcome: resource.outcome == null ? null : resource.outcome,
outcomeElement: resource.outcomeElement == null ? null : resource.outcomeElement,
decision: resource.decision == null ? null : resource.decision,
disposition: resource.disposition == null ? null : resource.disposition,
dispositionElement: resource.dispositionElement == null ? null : resource.dispositionElement,
preAuthRef: resource.preAuthRef == null ? null : resource.preAuthRef,
preAuthRefElement: resource.preAuthRefElement == null ? null : resource.preAuthRefElement,
preAuthPeriod: resource.preAuthPeriod == null ? null : resource.preAuthPeriod,
event: resource.event == null ? null : resource.event,
payeeType: resource.payeeType == null ? null : resource.payeeType,
encounter: resource.encounter == null ? null : resource.encounter,
diagnosisRelatedGroup: resource.diagnosisRelatedGroup == null ? null : resource.diagnosisRelatedGroup,
item: resource.item == null ? null : resource.item,
addItem: resource.addItem == null ? null : resource.addItem,
adjudication: resource.adjudication == null ? null : resource.adjudication,
total: resource.total == null ? null : resource.total,
payment: resource.payment == null ? null : resource.payment,
fundsReserve: resource.fundsReserve == null ? null : resource.fundsReserve,
formCode: resource.formCode == null ? null : resource.formCode,
form: resource.form == null ? null : resource.form,
processNote: resource.processNote == null ? null : resource.processNote,
communicationRequest: resource.communicationRequest == null ? null : resource.communicationRequest,
insurance: resource.insurance == null ? null : resource.insurance,
error: resource.error == null ? null : resource.error,

);
