import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.Claim claimlaimToServer(server.Claim resource) => client.Claim(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
traceNumber: resource.traceNumber == null ? null : resource.traceNumber,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
type: resource.type == null ? null : resource.type,
subType: resource.subType == null ? null : resource.subType,
use: resource.use == null ? null : resource.use,
useElement: resource.useElement == null ? null : resource.useElement,
patient: resource.patient == null ? null : resource.patient,
billablePeriod: resource.billablePeriod == null ? null : resource.billablePeriod,
created: resource.created == null ? null : resource.created,
createdElement: resource.createdElement == null ? null : resource.createdElement,
enterer: resource.enterer == null ? null : resource.enterer,
insurer: resource.insurer == null ? null : resource.insurer,
provider: resource.provider == null ? null : resource.provider,
priority: resource.priority == null ? null : resource.priority,
fundsReserve: resource.fundsReserve == null ? null : resource.fundsReserve,
related: resource.related == null ? null : resource.related,
prescription: resource.prescription == null ? null : resource.prescription,
originalPrescription: resource.originalPrescription == null ? null : resource.originalPrescription,
payee: resource.payee == null ? null : resource.payee,
referral: resource.referral == null ? null : resource.referral,
encounter: resource.encounter == null ? null : resource.encounter,
facility: resource.facility == null ? null : resource.facility,
diagnosisRelatedGroup: resource.diagnosisRelatedGroup == null ? null : resource.diagnosisRelatedGroup,
event: resource.event == null ? null : resource.event,
careTeam: resource.careTeam == null ? null : resource.careTeam,
supportingInfo: resource.supportingInfo == null ? null : resource.supportingInfo,
diagnosis: resource.diagnosis == null ? null : resource.diagnosis,
procedure: resource.procedure == null ? null : resource.procedure,
insurance: resource.insurance == null ? null : resource.insurance,
accident: resource.accident == null ? null : resource.accident,
patientPaid: resource.patientPaid == null ? null : resource.patientPaid,
item: resource.item == null ? null : resource.item,
total: resource.total == null ? null : resource.total,

);
