import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ClinicalImpression clinicalimpressionlinicalImpressionToServer(server.ClinicalImpression resource) => client.ClinicalImpression(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
statusReason: resource.statusReason == null ? null : resource.statusReason,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
subject: resource.subject == null ? null : resource.subject,
encounter: resource.encounter == null ? null : resource.encounter,
effectiveDateTime: resource.effectiveDateTime == null ? null : resource.effectiveDateTime,
effectiveDateTimeElement: resource.effectiveDateTimeElement == null ? null : resource.effectiveDateTimeElement,
effectivePeriod: resource.effectivePeriod == null ? null : resource.effectivePeriod,
date: resource.date == null ? null : resource.date,
dateElement: resource.dateElement == null ? null : resource.dateElement,
performer: resource.performer == null ? null : resource.performer,
previous: resource.previous == null ? null : resource.previous,
problem: resource.problem == null ? null : resource.problem,
changePattern: resource.changePattern == null ? null : resource.changePattern,
protocol: resource.protocol == null ? null : resource.protocol,
protocolElement: resource.protocolElement == null ? null : resource.protocolElement,
summary: resource.summary == null ? null : resource.summary,
summaryElement: resource.summaryElement == null ? null : resource.summaryElement,
finding: resource.finding == null ? null : resource.finding,
prognosisCodeableConcept: resource.prognosisCodeableConcept == null ? null : resource.prognosisCodeableConcept,
prognosisReference: resource.prognosisReference == null ? null : resource.prognosisReference,
supportingInfo: resource.supportingInfo == null ? null : resource.supportingInfo,
note: resource.note == null ? null : resource.note,

);
