import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.CommunicationRequest communicationrequestommunicationRequestToServer(server.CommunicationRequest resource) => client.CommunicationRequest(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
basedOn: resource.basedOn == null ? null : resource.basedOn,
replaces: resource.replaces == null ? null : resource.replaces,
groupIdentifier: resource.groupIdentifier == null ? null : resource.groupIdentifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
statusReason: resource.statusReason == null ? null : resource.statusReason,
intent: resource.intent == null ? null : resource.intent,
intentElement: resource.intentElement == null ? null : resource.intentElement,
category: resource.category == null ? null : resource.category,
priority: resource.priority == null ? null : resource.priority,
priorityElement: resource.priorityElement == null ? null : resource.priorityElement,
doNotPerform: resource.doNotPerform == null ? null : resource.doNotPerform,
doNotPerformElement: resource.doNotPerformElement == null ? null : resource.doNotPerformElement,
medium: resource.medium == null ? null : resource.medium,
subject: resource.subject == null ? null : resource.subject,
about: resource.about == null ? null : resource.about,
encounter: resource.encounter == null ? null : resource.encounter,
payload: resource.payload == null ? null : resource.payload,
occurrenceDateTime: resource.occurrenceDateTime == null ? null : resource.occurrenceDateTime,
occurrenceDateTimeElement: resource.occurrenceDateTimeElement == null ? null : resource.occurrenceDateTimeElement,
occurrencePeriod: resource.occurrencePeriod == null ? null : resource.occurrencePeriod,
authoredOn: resource.authoredOn == null ? null : resource.authoredOn,
authoredOnElement: resource.authoredOnElement == null ? null : resource.authoredOnElement,
requester: resource.requester == null ? null : resource.requester,
recipient: resource.recipient == null ? null : resource.recipient,
informationProvider: resource.informationProvider == null ? null : resource.informationProvider,
reason: resource.reason == null ? null : resource.reason,
note: resource.note == null ? null : resource.note,

);
