import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ContractValuedItem contractvalueditemontractValuedItemToServer(server.ContractValuedItem resource) => client.ContractValuedItem(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
entityCodeableConcept: resource.entityCodeableConcept == null ? null : resource.entityCodeableConcept,
entityReference: resource.entityReference == null ? null : resource.entityReference,
identifier: resource.identifier == null ? null : resource.identifier,
effectiveTime: resource.effectiveTime == null ? null : resource.effectiveTime,
effectiveTimeElement: resource.effectiveTimeElement == null ? null : resource.effectiveTimeElement,
quantity: resource.quantity == null ? null : resource.quantity,
unitPrice: resource.unitPrice == null ? null : resource.unitPrice,
factor: resource.factor == null ? null : resource.factor,
factorElement: resource.factorElement == null ? null : resource.factorElement,
points: resource.points == null ? null : resource.points,
pointsElement: resource.pointsElement == null ? null : resource.pointsElement,
net: resource.net == null ? null : resource.net,
payment: resource.payment == null ? null : resource.payment,
paymentElement: resource.paymentElement == null ? null : resource.paymentElement,
paymentDate: resource.paymentDate == null ? null : resource.paymentDate,
paymentDateElement: resource.paymentDateElement == null ? null : resource.paymentDateElement,
responsible: resource.responsible == null ? null : resource.responsible,
recipient: resource.recipient == null ? null : resource.recipient,
linkId: resource.linkId == null ? null : resource.linkId,
linkIdElement: resource.linkIdElement == null ? null : resource.linkIdElement,
securityLabelNumber: resource.securityLabelNumber == null ? null : resource.securityLabelNumber,
securityLabelNumberElement: resource.securityLabelNumberElement == null ? null : resource.securityLabelNumberElement,

);
