import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ContractAction contractactionontractActionToServer(server.ContractAction resource) => client.ContractAction(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
doNotPerform: resource.doNotPerform == null ? null : resource.doNotPerform,
doNotPerformElement: resource.doNotPerformElement == null ? null : resource.doNotPerformElement,
type: resource.type == null ? null : resource.type,
subject: resource.subject == null ? null : resource.subject,
intent: resource.intent == null ? null : resource.intent,
linkId: resource.linkId == null ? null : resource.linkId,
linkIdElement: resource.linkIdElement == null ? null : resource.linkIdElement,
status: resource.status == null ? null : resource.status,
context: resource.context == null ? null : resource.context,
contextLinkId: resource.contextLinkId == null ? null : resource.contextLinkId,
contextLinkIdElement: resource.contextLinkIdElement == null ? null : resource.contextLinkIdElement,
occurrenceDateTime: resource.occurrenceDateTime == null ? null : resource.occurrenceDateTime,
occurrenceDateTimeElement: resource.occurrenceDateTimeElement == null ? null : resource.occurrenceDateTimeElement,
occurrencePeriod: resource.occurrencePeriod == null ? null : resource.occurrencePeriod,
occurrenceTiming: resource.occurrenceTiming == null ? null : resource.occurrenceTiming,
requester: resource.requester == null ? null : resource.requester,
requesterLinkId: resource.requesterLinkId == null ? null : resource.requesterLinkId,
requesterLinkIdElement: resource.requesterLinkIdElement == null ? null : resource.requesterLinkIdElement,
performerType: resource.performerType == null ? null : resource.performerType,
performerRole: resource.performerRole == null ? null : resource.performerRole,
performer: resource.performer == null ? null : resource.performer,
performerLinkId: resource.performerLinkId == null ? null : resource.performerLinkId,
performerLinkIdElement: resource.performerLinkIdElement == null ? null : resource.performerLinkIdElement,
reason: resource.reason == null ? null : resource.reason,
reasonLinkId: resource.reasonLinkId == null ? null : resource.reasonLinkId,
reasonLinkIdElement: resource.reasonLinkIdElement == null ? null : resource.reasonLinkIdElement,
note: resource.note == null ? null : resource.note,
securityLabelNumber: resource.securityLabelNumber == null ? null : resource.securityLabelNumber,
securityLabelNumberElement: resource.securityLabelNumberElement == null ? null : resource.securityLabelNumberElement,

);
