import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.Coverage coverageoverageToServer(server.Coverage resource) => client.Coverage(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
kind: resource.kind == null ? null : resource.kind,
kindElement: resource.kindElement == null ? null : resource.kindElement,
paymentBy: resource.paymentBy == null ? null : resource.paymentBy,
type: resource.type == null ? null : resource.type,
policyHolder: resource.policyHolder == null ? null : resource.policyHolder,
subscriber: resource.subscriber == null ? null : resource.subscriber,
subscriberId: resource.subscriberId == null ? null : resource.subscriberId,
beneficiary: resource.beneficiary == null ? null : resource.beneficiary,
dependent: resource.dependent == null ? null : resource.dependent,
dependentElement: resource.dependentElement == null ? null : resource.dependentElement,
relationship: resource.relationship == null ? null : resource.relationship,
period: resource.period == null ? null : resource.period,
insurer: resource.insurer == null ? null : resource.insurer,
class_: resource.class_ == null ? null : resource.class_,
order: resource.order == null ? null : resource.order,
orderElement: resource.orderElement == null ? null : resource.orderElement,
network: resource.network == null ? null : resource.network,
networkElement: resource.networkElement == null ? null : resource.networkElement,
costToBeneficiary: resource.costToBeneficiary == null ? null : resource.costToBeneficiary,
subrogation: resource.subrogation == null ? null : resource.subrogation,
subrogationElement: resource.subrogationElement == null ? null : resource.subrogationElement,
contract: resource.contract == null ? null : resource.contract,
insurancePlan: resource.insurancePlan == null ? null : resource.insurancePlan,

);
