import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.CoverageEligibilityResponse coverageeligibilityresponseoverageEligibilityResponseToServer(server.CoverageEligibilityResponse resource) => client.CoverageEligibilityResponse(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
purpose: resource.purpose == null ? null : resource.purpose,
purposeElement: resource.purposeElement == null ? null : resource.purposeElement,
patient: resource.patient == null ? null : resource.patient,
event: resource.event == null ? null : resource.event,
servicedDate: resource.servicedDate == null ? null : resource.servicedDate,
servicedDateElement: resource.servicedDateElement == null ? null : resource.servicedDateElement,
servicedPeriod: resource.servicedPeriod == null ? null : resource.servicedPeriod,
created: resource.created == null ? null : resource.created,
createdElement: resource.createdElement == null ? null : resource.createdElement,
requestor: resource.requestor == null ? null : resource.requestor,
request: resource.request == null ? null : resource.request,
outcome: resource.outcome == null ? null : resource.outcome,
outcomeElement: resource.outcomeElement == null ? null : resource.outcomeElement,
disposition: resource.disposition == null ? null : resource.disposition,
dispositionElement: resource.dispositionElement == null ? null : resource.dispositionElement,
insurer: resource.insurer == null ? null : resource.insurer,
insurance: resource.insurance == null ? null : resource.insurance,
preAuthRef: resource.preAuthRef == null ? null : resource.preAuthRef,
preAuthRefElement: resource.preAuthRefElement == null ? null : resource.preAuthRefElement,
form: resource.form == null ? null : resource.form,
error: resource.error == null ? null : resource.error,

);
