import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.DetectedIssue detectedissueetectedIssueToServer(server.DetectedIssue resource) => client.DetectedIssue(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
category: resource.category == null ? null : resource.category,
code: resource.code == null ? null : resource.code,
severity: resource.severity == null ? null : resource.severity,
severityElement: resource.severityElement == null ? null : resource.severityElement,
subject: resource.subject == null ? null : resource.subject,
encounter: resource.encounter == null ? null : resource.encounter,
identifiedDateTime: resource.identifiedDateTime == null ? null : resource.identifiedDateTime,
identifiedDateTimeElement: resource.identifiedDateTimeElement == null ? null : resource.identifiedDateTimeElement,
identifiedPeriod: resource.identifiedPeriod == null ? null : resource.identifiedPeriod,
author: resource.author == null ? null : resource.author,
implicated: resource.implicated == null ? null : resource.implicated,
evidence: resource.evidence == null ? null : resource.evidence,
detail: resource.detail == null ? null : resource.detail,
detailElement: resource.detailElement == null ? null : resource.detailElement,
reference: resource.reference == null ? null : resource.reference,
referenceElement: resource.referenceElement == null ? null : resource.referenceElement,
mitigation: resource.mitigation == null ? null : resource.mitigation,

);
