import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.Device deviceeviceToServer(server.Device resource) => client.Device(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
displayName: resource.displayName == null ? null : resource.displayName,
displayNameElement: resource.displayNameElement == null ? null : resource.displayNameElement,
definition: resource.definition == null ? null : resource.definition,
udiCarrier: resource.udiCarrier == null ? null : resource.udiCarrier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
availabilityStatus: resource.availabilityStatus == null ? null : resource.availabilityStatus,
biologicalSourceEvent: resource.biologicalSourceEvent == null ? null : resource.biologicalSourceEvent,
manufacturer: resource.manufacturer == null ? null : resource.manufacturer,
manufacturerElement: resource.manufacturerElement == null ? null : resource.manufacturerElement,
manufactureDate: resource.manufactureDate == null ? null : resource.manufactureDate,
manufactureDateElement: resource.manufactureDateElement == null ? null : resource.manufactureDateElement,
expirationDate: resource.expirationDate == null ? null : resource.expirationDate,
expirationDateElement: resource.expirationDateElement == null ? null : resource.expirationDateElement,
lotNumber: resource.lotNumber == null ? null : resource.lotNumber,
lotNumberElement: resource.lotNumberElement == null ? null : resource.lotNumberElement,
serialNumber: resource.serialNumber == null ? null : resource.serialNumber,
serialNumberElement: resource.serialNumberElement == null ? null : resource.serialNumberElement,
name: resource.name == null ? null : resource.name,
modelNumber: resource.modelNumber == null ? null : resource.modelNumber,
modelNumberElement: resource.modelNumberElement == null ? null : resource.modelNumberElement,
partNumber: resource.partNumber == null ? null : resource.partNumber,
partNumberElement: resource.partNumberElement == null ? null : resource.partNumberElement,
category: resource.category == null ? null : resource.category,
type: resource.type == null ? null : resource.type,
version: resource.version == null ? null : resource.version,
conformsTo: resource.conformsTo == null ? null : resource.conformsTo,
property: resource.property == null ? null : resource.property,
mode: resource.mode == null ? null : resource.mode,
cycle: resource.cycle == null ? null : resource.cycle,
duration: resource.duration == null ? null : resource.duration,
owner: resource.owner == null ? null : resource.owner,
contact: resource.contact == null ? null : resource.contact,
location: resource.location == null ? null : resource.location,
url: resource.url == null ? null : resource.url,
urlElement: resource.urlElement == null ? null : resource.urlElement,
endpoint: resource.endpoint == null ? null : resource.endpoint,
gateway: resource.gateway == null ? null : resource.gateway,
note: resource.note == null ? null : resource.note,
safety: resource.safety == null ? null : resource.safety,
parent: resource.parent == null ? null : resource.parent,

);
