import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.DeviceDefinition devicedefinitioneviceDefinitionToServer(server.DeviceDefinition resource) => client.DeviceDefinition(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
identifier: resource.identifier == null ? null : resource.identifier,
udiDeviceIdentifier: resource.udiDeviceIdentifier == null ? null : resource.udiDeviceIdentifier,
regulatoryIdentifier: resource.regulatoryIdentifier == null ? null : resource.regulatoryIdentifier,
partNumber: resource.partNumber == null ? null : resource.partNumber,
partNumberElement: resource.partNumberElement == null ? null : resource.partNumberElement,
manufacturer: resource.manufacturer == null ? null : resource.manufacturer,
deviceName: resource.deviceName == null ? null : resource.deviceName,
modelNumber: resource.modelNumber == null ? null : resource.modelNumber,
modelNumberElement: resource.modelNumberElement == null ? null : resource.modelNumberElement,
classification: resource.classification == null ? null : resource.classification,
conformsTo: resource.conformsTo == null ? null : resource.conformsTo,
hasPart: resource.hasPart == null ? null : resource.hasPart,
packaging: resource.packaging == null ? null : resource.packaging,
version: resource.version == null ? null : resource.version,
safety: resource.safety == null ? null : resource.safety,
shelfLifeStorage: resource.shelfLifeStorage == null ? null : resource.shelfLifeStorage,
languageCode: resource.languageCode == null ? null : resource.languageCode,
property: resource.property == null ? null : resource.property,
owner: resource.owner == null ? null : resource.owner,
contact: resource.contact == null ? null : resource.contact,
link: resource.link == null ? null : resource.link,
note: resource.note == null ? null : resource.note,
material: resource.material == null ? null : resource.material,
productionIdentifierInUDI: resource.productionIdentifierInUDI == null ? null : resource.productionIdentifierInUDI,
productionIdentifierInUDIElement: resource.productionIdentifierInUDIElement == null ? null : resource.productionIdentifierInUDIElement,
guideline: resource.guideline == null ? null : resource.guideline,
correctiveAction: resource.correctiveAction == null ? null : resource.correctiveAction,
chargeItem: resource.chargeItem == null ? null : resource.chargeItem,

);
