import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.DiagnosticReport diagnosticreportiagnosticReportToServer(server.DiagnosticReport resource) => client.DiagnosticReport(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
basedOn: resource.basedOn == null ? null : resource.basedOn,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
category: resource.category == null ? null : resource.category,
code: resource.code == null ? null : resource.code,
subject: resource.subject == null ? null : resource.subject,
encounter: resource.encounter == null ? null : resource.encounter,
effectiveDateTime: resource.effectiveDateTime == null ? null : resource.effectiveDateTime,
effectiveDateTimeElement: resource.effectiveDateTimeElement == null ? null : resource.effectiveDateTimeElement,
effectivePeriod: resource.effectivePeriod == null ? null : resource.effectivePeriod,
issued: resource.issued == null ? null : resource.issued,
issuedElement: resource.issuedElement == null ? null : resource.issuedElement,
performer: resource.performer == null ? null : resource.performer,
resultsInterpreter: resource.resultsInterpreter == null ? null : resource.resultsInterpreter,
specimen: resource.specimen == null ? null : resource.specimen,
result: resource.result == null ? null : resource.result,
note: resource.note == null ? null : resource.note,
study: resource.study == null ? null : resource.study,
supportingInfo: resource.supportingInfo == null ? null : resource.supportingInfo,
media: resource.media == null ? null : resource.media,
composition: resource.composition == null ? null : resource.composition,
conclusion: resource.conclusion == null ? null : resource.conclusion,
conclusionElement: resource.conclusionElement == null ? null : resource.conclusionElement,
conclusionCode: resource.conclusionCode == null ? null : resource.conclusionCode,
presentedForm: resource.presentedForm == null ? null : resource.presentedForm,

);
