import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.DocumentReference documentreferenceocumentReferenceToServer(server.DocumentReference resource) => client.DocumentReference(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
version: resource.version == null ? null : resource.version,
versionElement: resource.versionElement == null ? null : resource.versionElement,
basedOn: resource.basedOn == null ? null : resource.basedOn,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
docStatus: resource.docStatus == null ? null : resource.docStatus,
docStatusElement: resource.docStatusElement == null ? null : resource.docStatusElement,
modality: resource.modality == null ? null : resource.modality,
type: resource.type == null ? null : resource.type,
category: resource.category == null ? null : resource.category,
subject: resource.subject == null ? null : resource.subject,
context: resource.context == null ? null : resource.context,
event: resource.event == null ? null : resource.event,
bodySite: resource.bodySite == null ? null : resource.bodySite,
facilityType: resource.facilityType == null ? null : resource.facilityType,
practiceSetting: resource.practiceSetting == null ? null : resource.practiceSetting,
period: resource.period == null ? null : resource.period,
date: resource.date == null ? null : resource.date,
dateElement: resource.dateElement == null ? null : resource.dateElement,
author: resource.author == null ? null : resource.author,
attester: resource.attester == null ? null : resource.attester,
custodian: resource.custodian == null ? null : resource.custodian,
relatesTo: resource.relatesTo == null ? null : resource.relatesTo,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
securityLabel: resource.securityLabel == null ? null : resource.securityLabel,
content: resource.content == null ? null : resource.content,

);
