import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ExplanationOfBenefitAddItem explanationofbenefitadditemxplanationOfBenefitAddItemToServer(server.ExplanationOfBenefitAddItem resource) => client.ExplanationOfBenefitAddItem(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
itemSequence: resource.itemSequence == null ? null : resource.itemSequence,
itemSequenceElement: resource.itemSequenceElement == null ? null : resource.itemSequenceElement,
detailSequence: resource.detailSequence == null ? null : resource.detailSequence,
detailSequenceElement: resource.detailSequenceElement == null ? null : resource.detailSequenceElement,
subDetailSequence: resource.subDetailSequence == null ? null : resource.subDetailSequence,
subDetailSequenceElement: resource.subDetailSequenceElement == null ? null : resource.subDetailSequenceElement,
traceNumber: resource.traceNumber == null ? null : resource.traceNumber,
provider: resource.provider == null ? null : resource.provider,
revenue: resource.revenue == null ? null : resource.revenue,
productOrService: resource.productOrService == null ? null : resource.productOrService,
productOrServiceEnd: resource.productOrServiceEnd == null ? null : resource.productOrServiceEnd,
request: resource.request == null ? null : resource.request,
modifier: resource.modifier == null ? null : resource.modifier,
programCode: resource.programCode == null ? null : resource.programCode,
servicedDate: resource.servicedDate == null ? null : resource.servicedDate,
servicedDateElement: resource.servicedDateElement == null ? null : resource.servicedDateElement,
servicedPeriod: resource.servicedPeriod == null ? null : resource.servicedPeriod,
locationCodeableConcept: resource.locationCodeableConcept == null ? null : resource.locationCodeableConcept,
locationAddress: resource.locationAddress == null ? null : resource.locationAddress,
locationReference: resource.locationReference == null ? null : resource.locationReference,
patientPaid: resource.patientPaid == null ? null : resource.patientPaid,
quantity: resource.quantity == null ? null : resource.quantity,
unitPrice: resource.unitPrice == null ? null : resource.unitPrice,
factor: resource.factor == null ? null : resource.factor,
factorElement: resource.factorElement == null ? null : resource.factorElement,
tax: resource.tax == null ? null : resource.tax,
net: resource.net == null ? null : resource.net,
bodySite: resource.bodySite == null ? null : resource.bodySite,
noteNumber: resource.noteNumber == null ? null : resource.noteNumber,
noteNumberElement: resource.noteNumberElement == null ? null : resource.noteNumberElement,
reviewOutcome: resource.reviewOutcome == null ? null : resource.reviewOutcome,
adjudication: resource.adjudication == null ? null : resource.adjudication,
detail: resource.detail == null ? null : resource.detail,

);
