import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ExplanationOfBenefitItem explanationofbenefititemxplanationOfBenefitItemToServer(server.ExplanationOfBenefitItem resource) => client.ExplanationOfBenefitItem(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
sequence: resource.sequence == null ? null : resource.sequence,
sequenceElement: resource.sequenceElement == null ? null : resource.sequenceElement,
careTeamSequence: resource.careTeamSequence == null ? null : resource.careTeamSequence,
careTeamSequenceElement: resource.careTeamSequenceElement == null ? null : resource.careTeamSequenceElement,
diagnosisSequence: resource.diagnosisSequence == null ? null : resource.diagnosisSequence,
diagnosisSequenceElement: resource.diagnosisSequenceElement == null ? null : resource.diagnosisSequenceElement,
procedureSequence: resource.procedureSequence == null ? null : resource.procedureSequence,
procedureSequenceElement: resource.procedureSequenceElement == null ? null : resource.procedureSequenceElement,
informationSequence: resource.informationSequence == null ? null : resource.informationSequence,
informationSequenceElement: resource.informationSequenceElement == null ? null : resource.informationSequenceElement,
traceNumber: resource.traceNumber == null ? null : resource.traceNumber,
revenue: resource.revenue == null ? null : resource.revenue,
category: resource.category == null ? null : resource.category,
productOrService: resource.productOrService == null ? null : resource.productOrService,
productOrServiceEnd: resource.productOrServiceEnd == null ? null : resource.productOrServiceEnd,
request: resource.request == null ? null : resource.request,
modifier: resource.modifier == null ? null : resource.modifier,
programCode: resource.programCode == null ? null : resource.programCode,
servicedDate: resource.servicedDate == null ? null : resource.servicedDate,
servicedDateElement: resource.servicedDateElement == null ? null : resource.servicedDateElement,
servicedPeriod: resource.servicedPeriod == null ? null : resource.servicedPeriod,
locationCodeableConcept: resource.locationCodeableConcept == null ? null : resource.locationCodeableConcept,
locationAddress: resource.locationAddress == null ? null : resource.locationAddress,
locationReference: resource.locationReference == null ? null : resource.locationReference,
patientPaid: resource.patientPaid == null ? null : resource.patientPaid,
quantity: resource.quantity == null ? null : resource.quantity,
unitPrice: resource.unitPrice == null ? null : resource.unitPrice,
factor: resource.factor == null ? null : resource.factor,
factorElement: resource.factorElement == null ? null : resource.factorElement,
tax: resource.tax == null ? null : resource.tax,
net: resource.net == null ? null : resource.net,
udi: resource.udi == null ? null : resource.udi,
bodySite: resource.bodySite == null ? null : resource.bodySite,
encounter: resource.encounter == null ? null : resource.encounter,
noteNumber: resource.noteNumber == null ? null : resource.noteNumber,
noteNumberElement: resource.noteNumberElement == null ? null : resource.noteNumberElement,
reviewOutcome: resource.reviewOutcome == null ? null : resource.reviewOutcome,
adjudication: resource.adjudication == null ? null : resource.adjudication,
detail: resource.detail == null ? null : resource.detail,

);
