import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.HealthcareService healthcareserviceealthcareServiceToServer(server.HealthcareService resource) => client.HealthcareService(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
active: resource.active == null ? null : resource.active,
activeElement: resource.activeElement == null ? null : resource.activeElement,
providedBy: resource.providedBy == null ? null : resource.providedBy,
offeredIn: resource.offeredIn == null ? null : resource.offeredIn,
category: resource.category == null ? null : resource.category,
type: resource.type == null ? null : resource.type,
specialty: resource.specialty == null ? null : resource.specialty,
location: resource.location == null ? null : resource.location,
name: resource.name == null ? null : resource.name,
nameElement: resource.nameElement == null ? null : resource.nameElement,
comment: resource.comment == null ? null : resource.comment,
commentElement: resource.commentElement == null ? null : resource.commentElement,
extraDetails: resource.extraDetails == null ? null : resource.extraDetails,
extraDetailsElement: resource.extraDetailsElement == null ? null : resource.extraDetailsElement,
photo: resource.photo == null ? null : resource.photo,
contact: resource.contact == null ? null : resource.contact,
coverageArea: resource.coverageArea == null ? null : resource.coverageArea,
serviceProvisionCode: resource.serviceProvisionCode == null ? null : resource.serviceProvisionCode,
eligibility: resource.eligibility == null ? null : resource.eligibility,
program: resource.program == null ? null : resource.program,
characteristic: resource.characteristic == null ? null : resource.characteristic,
communication: resource.communication == null ? null : resource.communication,
referralMethod: resource.referralMethod == null ? null : resource.referralMethod,
appointmentRequired: resource.appointmentRequired == null ? null : resource.appointmentRequired,
appointmentRequiredElement: resource.appointmentRequiredElement == null ? null : resource.appointmentRequiredElement,
availability: resource.availability == null ? null : resource.availability,
endpoint: resource.endpoint == null ? null : resource.endpoint,

);
