import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ImagingSelection imagingselectionmagingSelectionToServer(server.ImagingSelection resource) => client.ImagingSelection(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
subject: resource.subject == null ? null : resource.subject,
issued: resource.issued == null ? null : resource.issued,
issuedElement: resource.issuedElement == null ? null : resource.issuedElement,
performer: resource.performer == null ? null : resource.performer,
basedOn: resource.basedOn == null ? null : resource.basedOn,
category: resource.category == null ? null : resource.category,
code: resource.code == null ? null : resource.code,
studyUid: resource.studyUid == null ? null : resource.studyUid,
studyUidElement: resource.studyUidElement == null ? null : resource.studyUidElement,
derivedFrom: resource.derivedFrom == null ? null : resource.derivedFrom,
endpoint: resource.endpoint == null ? null : resource.endpoint,
seriesUid: resource.seriesUid == null ? null : resource.seriesUid,
seriesUidElement: resource.seriesUidElement == null ? null : resource.seriesUidElement,
seriesNumber: resource.seriesNumber == null ? null : resource.seriesNumber,
seriesNumberElement: resource.seriesNumberElement == null ? null : resource.seriesNumberElement,
frameOfReferenceUid: resource.frameOfReferenceUid == null ? null : resource.frameOfReferenceUid,
frameOfReferenceUidElement: resource.frameOfReferenceUidElement == null ? null : resource.frameOfReferenceUidElement,
bodySite: resource.bodySite == null ? null : resource.bodySite,
focus: resource.focus == null ? null : resource.focus,
instance: resource.instance == null ? null : resource.instance,

);
