import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ImmunizationEvaluation immunizationevaluationmmunizationEvaluationToServer(server.ImmunizationEvaluation resource) => client.ImmunizationEvaluation(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
patient: resource.patient == null ? null : resource.patient,
date: resource.date == null ? null : resource.date,
dateElement: resource.dateElement == null ? null : resource.dateElement,
authority: resource.authority == null ? null : resource.authority,
targetDisease: resource.targetDisease == null ? null : resource.targetDisease,
immunizationEvent: resource.immunizationEvent == null ? null : resource.immunizationEvent,
doseStatus: resource.doseStatus == null ? null : resource.doseStatus,
doseStatusReason: resource.doseStatusReason == null ? null : resource.doseStatusReason,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
series: resource.series == null ? null : resource.series,
seriesElement: resource.seriesElement == null ? null : resource.seriesElement,
doseNumber: resource.doseNumber == null ? null : resource.doseNumber,
doseNumberElement: resource.doseNumberElement == null ? null : resource.doseNumberElement,
seriesDoses: resource.seriesDoses == null ? null : resource.seriesDoses,
seriesDosesElement: resource.seriesDosesElement == null ? null : resource.seriesDosesElement,

);
