import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.Immunization immunizationmmunizationToServer(server.Immunization resource) => client.Immunization(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
basedOn: resource.basedOn == null ? null : resource.basedOn,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
statusReason: resource.statusReason == null ? null : resource.statusReason,
vaccineCode: resource.vaccineCode == null ? null : resource.vaccineCode,
administeredProduct: resource.administeredProduct == null ? null : resource.administeredProduct,
manufacturer: resource.manufacturer == null ? null : resource.manufacturer,
lotNumber: resource.lotNumber == null ? null : resource.lotNumber,
lotNumberElement: resource.lotNumberElement == null ? null : resource.lotNumberElement,
expirationDate: resource.expirationDate == null ? null : resource.expirationDate,
expirationDateElement: resource.expirationDateElement == null ? null : resource.expirationDateElement,
patient: resource.patient == null ? null : resource.patient,
encounter: resource.encounter == null ? null : resource.encounter,
supportingInformation: resource.supportingInformation == null ? null : resource.supportingInformation,
occurrenceDateTime: resource.occurrenceDateTime == null ? null : resource.occurrenceDateTime,
occurrenceDateTimeElement: resource.occurrenceDateTimeElement == null ? null : resource.occurrenceDateTimeElement,
occurrenceString: resource.occurrenceString == null ? null : resource.occurrenceString,
occurrenceStringElement: resource.occurrenceStringElement == null ? null : resource.occurrenceStringElement,
primarySource: resource.primarySource == null ? null : resource.primarySource,
primarySourceElement: resource.primarySourceElement == null ? null : resource.primarySourceElement,
informationSource: resource.informationSource == null ? null : resource.informationSource,
location: resource.location == null ? null : resource.location,
site: resource.site == null ? null : resource.site,
route: resource.route == null ? null : resource.route,
doseQuantity: resource.doseQuantity == null ? null : resource.doseQuantity,
performer: resource.performer == null ? null : resource.performer,
note: resource.note == null ? null : resource.note,
reason: resource.reason == null ? null : resource.reason,
isSubpotent: resource.isSubpotent == null ? null : resource.isSubpotent,
isSubpotentElement: resource.isSubpotentElement == null ? null : resource.isSubpotentElement,
subpotentReason: resource.subpotentReason == null ? null : resource.subpotentReason,
programEligibility: resource.programEligibility == null ? null : resource.programEligibility,
fundingSource: resource.fundingSource == null ? null : resource.fundingSource,
reaction: resource.reaction == null ? null : resource.reaction,
protocolApplied: resource.protocolApplied == null ? null : resource.protocolApplied,

);
