import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.Invoice invoicenvoiceToServer(server.Invoice resource) => client.Invoice(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
cancelledReason: resource.cancelledReason == null ? null : resource.cancelledReason,
cancelledReasonElement: resource.cancelledReasonElement == null ? null : resource.cancelledReasonElement,
type: resource.type == null ? null : resource.type,
subject: resource.subject == null ? null : resource.subject,
recipient: resource.recipient == null ? null : resource.recipient,
date: resource.date == null ? null : resource.date,
dateElement: resource.dateElement == null ? null : resource.dateElement,
creation: resource.creation == null ? null : resource.creation,
creationElement: resource.creationElement == null ? null : resource.creationElement,
periodDate: resource.periodDate == null ? null : resource.periodDate,
periodDateElement: resource.periodDateElement == null ? null : resource.periodDateElement,
periodPeriod: resource.periodPeriod == null ? null : resource.periodPeriod,
participant: resource.participant == null ? null : resource.participant,
issuer: resource.issuer == null ? null : resource.issuer,
account: resource.account == null ? null : resource.account,
lineItem: resource.lineItem == null ? null : resource.lineItem,
totalPriceComponent: resource.totalPriceComponent == null ? null : resource.totalPriceComponent,
totalNet: resource.totalNet == null ? null : resource.totalNet,
totalGross: resource.totalGross == null ? null : resource.totalGross,
paymentTerms: resource.paymentTerms == null ? null : resource.paymentTerms,
paymentTermsElement: resource.paymentTermsElement == null ? null : resource.paymentTermsElement,
note: resource.note == null ? null : resource.note,

);
