import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.MedicationStatement medicationstatementedicationStatementToServer(server.MedicationStatement resource) => client.MedicationStatement(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
partOf: resource.partOf == null ? null : resource.partOf,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
category: resource.category == null ? null : resource.category,
medication: resource.medication == null ? null : resource.medication,
subject: resource.subject == null ? null : resource.subject,
encounter: resource.encounter == null ? null : resource.encounter,
effectiveDateTime: resource.effectiveDateTime == null ? null : resource.effectiveDateTime,
effectiveDateTimeElement: resource.effectiveDateTimeElement == null ? null : resource.effectiveDateTimeElement,
effectivePeriod: resource.effectivePeriod == null ? null : resource.effectivePeriod,
effectiveTiming: resource.effectiveTiming == null ? null : resource.effectiveTiming,
dateAsserted: resource.dateAsserted == null ? null : resource.dateAsserted,
dateAssertedElement: resource.dateAssertedElement == null ? null : resource.dateAssertedElement,
informationSource: resource.informationSource == null ? null : resource.informationSource,
derivedFrom: resource.derivedFrom == null ? null : resource.derivedFrom,
reason: resource.reason == null ? null : resource.reason,
note: resource.note == null ? null : resource.note,
relatedClinicalInformation: resource.relatedClinicalInformation == null ? null : resource.relatedClinicalInformation,
renderedDosageInstruction: resource.renderedDosageInstruction == null ? null : resource.renderedDosageInstruction,
renderedDosageInstructionElement: resource.renderedDosageInstructionElement == null ? null : resource.renderedDosageInstructionElement,
dosage: resource.dosage == null ? null : resource.dosage,
adherence: resource.adherence == null ? null : resource.adherence,

);
