import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.MedicationRequest medicationrequestedicationRequestToServer(server.MedicationRequest resource) => client.MedicationRequest(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
basedOn: resource.basedOn == null ? null : resource.basedOn,
priorPrescription: resource.priorPrescription == null ? null : resource.priorPrescription,
groupIdentifier: resource.groupIdentifier == null ? null : resource.groupIdentifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
statusReason: resource.statusReason == null ? null : resource.statusReason,
statusChanged: resource.statusChanged == null ? null : resource.statusChanged,
statusChangedElement: resource.statusChangedElement == null ? null : resource.statusChangedElement,
intent: resource.intent == null ? null : resource.intent,
intentElement: resource.intentElement == null ? null : resource.intentElement,
category: resource.category == null ? null : resource.category,
priority: resource.priority == null ? null : resource.priority,
priorityElement: resource.priorityElement == null ? null : resource.priorityElement,
doNotPerform: resource.doNotPerform == null ? null : resource.doNotPerform,
doNotPerformElement: resource.doNotPerformElement == null ? null : resource.doNotPerformElement,
medication: resource.medication == null ? null : resource.medication,
subject: resource.subject == null ? null : resource.subject,
informationSource: resource.informationSource == null ? null : resource.informationSource,
encounter: resource.encounter == null ? null : resource.encounter,
supportingInformation: resource.supportingInformation == null ? null : resource.supportingInformation,
authoredOn: resource.authoredOn == null ? null : resource.authoredOn,
authoredOnElement: resource.authoredOnElement == null ? null : resource.authoredOnElement,
requester: resource.requester == null ? null : resource.requester,
reported: resource.reported == null ? null : resource.reported,
reportedElement: resource.reportedElement == null ? null : resource.reportedElement,
performerType: resource.performerType == null ? null : resource.performerType,
performer: resource.performer == null ? null : resource.performer,
device: resource.device == null ? null : resource.device,
recorder: resource.recorder == null ? null : resource.recorder,
reason: resource.reason == null ? null : resource.reason,
courseOfTherapyType: resource.courseOfTherapyType == null ? null : resource.courseOfTherapyType,
insurance: resource.insurance == null ? null : resource.insurance,
note: resource.note == null ? null : resource.note,
renderedDosageInstruction: resource.renderedDosageInstruction == null ? null : resource.renderedDosageInstruction,
renderedDosageInstructionElement: resource.renderedDosageInstructionElement == null ? null : resource.renderedDosageInstructionElement,
effectiveDosePeriod: resource.effectiveDosePeriod == null ? null : resource.effectiveDosePeriod,
dosageInstruction: resource.dosageInstruction == null ? null : resource.dosageInstruction,
dispenseRequest: resource.dispenseRequest == null ? null : resource.dispenseRequest,
substitution: resource.substitution == null ? null : resource.substitution,
eventHistory: resource.eventHistory == null ? null : resource.eventHistory,

);
