import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.MedicinalProductDefinition medicinalproductdefinitionedicinalProductDefinitionToServer(server.MedicinalProductDefinition resource) => client.MedicinalProductDefinition(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
type: resource.type == null ? null : resource.type,
domain: resource.domain == null ? null : resource.domain,
version: resource.version == null ? null : resource.version,
versionElement: resource.versionElement == null ? null : resource.versionElement,
status: resource.status == null ? null : resource.status,
statusDate: resource.statusDate == null ? null : resource.statusDate,
statusDateElement: resource.statusDateElement == null ? null : resource.statusDateElement,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
combinedPharmaceuticalDoseForm: resource.combinedPharmaceuticalDoseForm == null ? null : resource.combinedPharmaceuticalDoseForm,
route: resource.route == null ? null : resource.route,
indication: resource.indication == null ? null : resource.indication,
indicationElement: resource.indicationElement == null ? null : resource.indicationElement,
legalStatusOfSupply: resource.legalStatusOfSupply == null ? null : resource.legalStatusOfSupply,
additionalMonitoringIndicator: resource.additionalMonitoringIndicator == null ? null : resource.additionalMonitoringIndicator,
specialMeasures: resource.specialMeasures == null ? null : resource.specialMeasures,
pediatricUseIndicator: resource.pediatricUseIndicator == null ? null : resource.pediatricUseIndicator,
classification: resource.classification == null ? null : resource.classification,
marketingStatus: resource.marketingStatus == null ? null : resource.marketingStatus,
packagedMedicinalProduct: resource.packagedMedicinalProduct == null ? null : resource.packagedMedicinalProduct,
comprisedOf: resource.comprisedOf == null ? null : resource.comprisedOf,
ingredient: resource.ingredient == null ? null : resource.ingredient,
impurity: resource.impurity == null ? null : resource.impurity,
attachedDocument: resource.attachedDocument == null ? null : resource.attachedDocument,
masterFile: resource.masterFile == null ? null : resource.masterFile,
contact: resource.contact == null ? null : resource.contact,
clinicalTrial: resource.clinicalTrial == null ? null : resource.clinicalTrial,
code: resource.code == null ? null : resource.code,
name: resource.name == null ? null : resource.name,
crossReference: resource.crossReference == null ? null : resource.crossReference,
operation: resource.operation == null ? null : resource.operation,
characteristic: resource.characteristic == null ? null : resource.characteristic,

);
