import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.NutritionOrder nutritionorderutritionOrderToServer(server.NutritionOrder resource) => client.NutritionOrder(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
instantiatesCanonical: resource.instantiatesCanonical == null ? null : resource.instantiatesCanonical,
instantiatesUri: resource.instantiatesUri == null ? null : resource.instantiatesUri,
instantiatesUriElement: resource.instantiatesUriElement == null ? null : resource.instantiatesUriElement,
instantiates: resource.instantiates == null ? null : resource.instantiates,
instantiatesElement: resource.instantiatesElement == null ? null : resource.instantiatesElement,
basedOn: resource.basedOn == null ? null : resource.basedOn,
groupIdentifier: resource.groupIdentifier == null ? null : resource.groupIdentifier,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
intent: resource.intent == null ? null : resource.intent,
intentElement: resource.intentElement == null ? null : resource.intentElement,
priority: resource.priority == null ? null : resource.priority,
priorityElement: resource.priorityElement == null ? null : resource.priorityElement,
subject: resource.subject == null ? null : resource.subject,
encounter: resource.encounter == null ? null : resource.encounter,
supportingInformation: resource.supportingInformation == null ? null : resource.supportingInformation,
dateTime: resource.dateTime == null ? null : resource.dateTime,
dateTimeElement: resource.dateTimeElement == null ? null : resource.dateTimeElement,
orderer: resource.orderer == null ? null : resource.orderer,
performer: resource.performer == null ? null : resource.performer,
allergyIntolerance: resource.allergyIntolerance == null ? null : resource.allergyIntolerance,
foodPreferenceModifier: resource.foodPreferenceModifier == null ? null : resource.foodPreferenceModifier,
excludeFoodModifier: resource.excludeFoodModifier == null ? null : resource.excludeFoodModifier,
outsideFoodAllowed: resource.outsideFoodAllowed == null ? null : resource.outsideFoodAllowed,
outsideFoodAllowedElement: resource.outsideFoodAllowedElement == null ? null : resource.outsideFoodAllowedElement,
oralDiet: resource.oralDiet == null ? null : resource.oralDiet,
supplement: resource.supplement == null ? null : resource.supplement,
enteralFormula: resource.enteralFormula == null ? null : resource.enteralFormula,
note: resource.note == null ? null : resource.note,

);
