import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.OperationDefinitionParameter operationdefinitionparameterperationDefinitionParameterToServer(server.OperationDefinitionParameter resource) => client.OperationDefinitionParameter(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
name: resource.name == null ? null : resource.name,
nameElement: resource.nameElement == null ? null : resource.nameElement,
use: resource.use == null ? null : resource.use,
useElement: resource.useElement == null ? null : resource.useElement,
scope: resource.scope == null ? null : resource.scope,
scopeElement: resource.scopeElement == null ? null : resource.scopeElement,
min: resource.min == null ? null : resource.min,
minElement: resource.minElement == null ? null : resource.minElement,
max: resource.max == null ? null : resource.max,
maxElement: resource.maxElement == null ? null : resource.maxElement,
documentation: resource.documentation == null ? null : resource.documentation,
documentationElement: resource.documentationElement == null ? null : resource.documentationElement,
type: resource.type == null ? null : resource.type,
typeElement: resource.typeElement == null ? null : resource.typeElement,
allowedType: resource.allowedType == null ? null : resource.allowedType,
allowedTypeElement: resource.allowedTypeElement == null ? null : resource.allowedTypeElement,
targetProfile: resource.targetProfile == null ? null : resource.targetProfile,
searchType: resource.searchType == null ? null : resource.searchType,
searchTypeElement: resource.searchTypeElement == null ? null : resource.searchTypeElement,
binding: resource.binding == null ? null : resource.binding,
referencedFrom: resource.referencedFrom == null ? null : resource.referencedFrom,
part_: resource.part_ == null ? null : resource.part_,

);
