import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.ResearchStudy researchstudyesearchStudyToServer(server.ResearchStudy resource) => client.ResearchStudy(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
url: resource.url == null ? null : resource.url,
urlElement: resource.urlElement == null ? null : resource.urlElement,
identifier: resource.identifier == null ? null : resource.identifier,
version: resource.version == null ? null : resource.version,
versionElement: resource.versionElement == null ? null : resource.versionElement,
name: resource.name == null ? null : resource.name,
nameElement: resource.nameElement == null ? null : resource.nameElement,
title: resource.title == null ? null : resource.title,
titleElement: resource.titleElement == null ? null : resource.titleElement,
label: resource.label == null ? null : resource.label,
protocol: resource.protocol == null ? null : resource.protocol,
partOf: resource.partOf == null ? null : resource.partOf,
relatedArtifact: resource.relatedArtifact == null ? null : resource.relatedArtifact,
date: resource.date == null ? null : resource.date,
dateElement: resource.dateElement == null ? null : resource.dateElement,
status: resource.status == null ? null : resource.status,
statusElement: resource.statusElement == null ? null : resource.statusElement,
primaryPurposeType: resource.primaryPurposeType == null ? null : resource.primaryPurposeType,
phase: resource.phase == null ? null : resource.phase,
studyDesign: resource.studyDesign == null ? null : resource.studyDesign,
focus: resource.focus == null ? null : resource.focus,
condition: resource.condition == null ? null : resource.condition,
keyword: resource.keyword == null ? null : resource.keyword,
region: resource.region == null ? null : resource.region,
descriptionSummary: resource.descriptionSummary == null ? null : resource.descriptionSummary,
descriptionSummaryElement: resource.descriptionSummaryElement == null ? null : resource.descriptionSummaryElement,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
period: resource.period == null ? null : resource.period,
site: resource.site == null ? null : resource.site,
note: resource.note == null ? null : resource.note,
classifier: resource.classifier == null ? null : resource.classifier,
associatedParty: resource.associatedParty == null ? null : resource.associatedParty,
progressStatus: resource.progressStatus == null ? null : resource.progressStatus,
whyStopped: resource.whyStopped == null ? null : resource.whyStopped,
recruitment: resource.recruitment == null ? null : resource.recruitment,
comparisonGroup: resource.comparisonGroup == null ? null : resource.comparisonGroup,
objective: resource.objective == null ? null : resource.objective,
outcomeMeasure: resource.outcomeMeasure == null ? null : resource.outcomeMeasure,
result: resource.result == null ? null : resource.result,

);
