import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.SubstanceDefinition substancedefinitionubstanceDefinitionToServer(server.SubstanceDefinition resource) => client.SubstanceDefinition(

id: resource.id == null ? null : resource.id,
meta: resource.meta == null ? null : resource.meta,
implicitRules: resource.implicitRules == null ? null : resource.implicitRules,
implicitRulesElement: resource.implicitRulesElement == null ? null : resource.implicitRulesElement,
language: resource.language == null ? null : resource.language,
languageElement: resource.languageElement == null ? null : resource.languageElement,
text: resource.text == null ? null : resource.text,
contained: resource.contained == null ? null : resource.contained,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
identifier: resource.identifier == null ? null : resource.identifier,
version: resource.version == null ? null : resource.version,
versionElement: resource.versionElement == null ? null : resource.versionElement,
status: resource.status == null ? null : resource.status,
classification: resource.classification == null ? null : resource.classification,
domain: resource.domain == null ? null : resource.domain,
grade: resource.grade == null ? null : resource.grade,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
informationSource: resource.informationSource == null ? null : resource.informationSource,
note: resource.note == null ? null : resource.note,
manufacturer: resource.manufacturer == null ? null : resource.manufacturer,
supplier: resource.supplier == null ? null : resource.supplier,
moiety: resource.moiety == null ? null : resource.moiety,
characterization: resource.characterization == null ? null : resource.characterization,
property: resource.property == null ? null : resource.property,
referenceInformation: resource.referenceInformation == null ? null : resource.referenceInformation,
molecularWeight: resource.molecularWeight == null ? null : resource.molecularWeight,
structure: resource.structure == null ? null : resource.structure,
code: resource.code == null ? null : resource.code,
name: resource.name == null ? null : resource.name,
relationship: resource.relationship == null ? null : resource.relationship,
nucleicAcid: resource.nucleicAcid == null ? null : resource.nucleicAcid,
polymer: resource.polymer == null ? null : resource.polymer,
protein: resource.protein == null ? null : resource.protein,
sourceMaterial: resource.sourceMaterial == null ? null : resource.sourceMaterial,

);
