import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.TestScriptOperation testscriptoperationestScriptOperationToServer(server.TestScriptOperation resource) => client.TestScriptOperation(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
type: resource.type == null ? null : resource.type,
resource: resource.resource == null ? null : resource.resource,
resourceElement: resource.resourceElement == null ? null : resource.resourceElement,
label: resource.label == null ? null : resource.label,
labelElement: resource.labelElement == null ? null : resource.labelElement,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
accept: resource.accept == null ? null : resource.accept,
acceptElement: resource.acceptElement == null ? null : resource.acceptElement,
contentType: resource.contentType == null ? null : resource.contentType,
contentTypeElement: resource.contentTypeElement == null ? null : resource.contentTypeElement,
destination: resource.destination == null ? null : resource.destination,
destinationElement: resource.destinationElement == null ? null : resource.destinationElement,
encodeRequestUrl: resource.encodeRequestUrl == null ? null : resource.encodeRequestUrl,
encodeRequestUrlElement: resource.encodeRequestUrlElement == null ? null : resource.encodeRequestUrlElement,
method: resource.method == null ? null : resource.method,
methodElement: resource.methodElement == null ? null : resource.methodElement,
origin: resource.origin == null ? null : resource.origin,
originElement: resource.originElement == null ? null : resource.originElement,
params: resource.params == null ? null : resource.params,
paramsElement: resource.paramsElement == null ? null : resource.paramsElement,
requestHeader: resource.requestHeader == null ? null : resource.requestHeader,
requestId: resource.requestId == null ? null : resource.requestId,
requestIdElement: resource.requestIdElement == null ? null : resource.requestIdElement,
responseId: resource.responseId == null ? null : resource.responseId,
responseIdElement: resource.responseIdElement == null ? null : resource.responseIdElement,
sourceId: resource.sourceId == null ? null : resource.sourceId,
sourceIdElement: resource.sourceIdElement == null ? null : resource.sourceIdElement,
targetId: resource.targetId == null ? null : resource.targetId,
targetIdElement: resource.targetIdElement == null ? null : resource.targetIdElement,
url: resource.url == null ? null : resource.url,
urlElement: resource.urlElement == null ? null : resource.urlElement,

);
