import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.TestScriptAssert testscriptassertestScriptAssertToServer(server.TestScriptAssert resource) => client.TestScriptAssert(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
label: resource.label == null ? null : resource.label,
labelElement: resource.labelElement == null ? null : resource.labelElement,
description: resource.description == null ? null : resource.description,
descriptionElement: resource.descriptionElement == null ? null : resource.descriptionElement,
direction: resource.direction == null ? null : resource.direction,
directionElement: resource.directionElement == null ? null : resource.directionElement,
compareToSourceId: resource.compareToSourceId == null ? null : resource.compareToSourceId,
compareToSourceIdElement: resource.compareToSourceIdElement == null ? null : resource.compareToSourceIdElement,
compareToSourceExpression: resource.compareToSourceExpression == null ? null : resource.compareToSourceExpression,
compareToSourceExpressionElement: resource.compareToSourceExpressionElement == null ? null : resource.compareToSourceExpressionElement,
compareToSourcePath: resource.compareToSourcePath == null ? null : resource.compareToSourcePath,
compareToSourcePathElement: resource.compareToSourcePathElement == null ? null : resource.compareToSourcePathElement,
contentType: resource.contentType == null ? null : resource.contentType,
contentTypeElement: resource.contentTypeElement == null ? null : resource.contentTypeElement,
defaultManualCompletion: resource.defaultManualCompletion == null ? null : resource.defaultManualCompletion,
defaultManualCompletionElement: resource.defaultManualCompletionElement == null ? null : resource.defaultManualCompletionElement,
expression: resource.expression == null ? null : resource.expression,
expressionElement: resource.expressionElement == null ? null : resource.expressionElement,
headerField: resource.headerField == null ? null : resource.headerField,
headerFieldElement: resource.headerFieldElement == null ? null : resource.headerFieldElement,
minimumId: resource.minimumId == null ? null : resource.minimumId,
minimumIdElement: resource.minimumIdElement == null ? null : resource.minimumIdElement,
navigationLinks: resource.navigationLinks == null ? null : resource.navigationLinks,
navigationLinksElement: resource.navigationLinksElement == null ? null : resource.navigationLinksElement,
operator_: resource.operator_ == null ? null : resource.operator_,
operatorElement: resource.operatorElement == null ? null : resource.operatorElement,
path: resource.path == null ? null : resource.path,
pathElement: resource.pathElement == null ? null : resource.pathElement,
requestMethod: resource.requestMethod == null ? null : resource.requestMethod,
requestMethodElement: resource.requestMethodElement == null ? null : resource.requestMethodElement,
requestURL: resource.requestURL == null ? null : resource.requestURL,
requestURLElement: resource.requestURLElement == null ? null : resource.requestURLElement,
resource: resource.resource == null ? null : resource.resource,
resourceElement: resource.resourceElement == null ? null : resource.resourceElement,
response: resource.response == null ? null : resource.response,
responseElement: resource.responseElement == null ? null : resource.responseElement,
responseCode: resource.responseCode == null ? null : resource.responseCode,
responseCodeElement: resource.responseCodeElement == null ? null : resource.responseCodeElement,
sourceId: resource.sourceId == null ? null : resource.sourceId,
sourceIdElement: resource.sourceIdElement == null ? null : resource.sourceIdElement,
stopTestOnFail: resource.stopTestOnFail == null ? null : resource.stopTestOnFail,
stopTestOnFailElement: resource.stopTestOnFailElement == null ? null : resource.stopTestOnFailElement,
validateProfileId: resource.validateProfileId == null ? null : resource.validateProfileId,
validateProfileIdElement: resource.validateProfileIdElement == null ? null : resource.validateProfileIdElement,
value: resource.value == null ? null : resource.value,
valueElement: resource.valueElement == null ? null : resource.valueElement,
warningOnly: resource.warningOnly == null ? null : resource.warningOnly,
warningOnlyElement: resource.warningOnlyElement == null ? null : resource.warningOnlyElement,
requirement: resource.requirement == null ? null : resource.requirement,

);
