import 'package:fhir/r5.dart' as client;
import 'package:fhirpod_server/src/generated/protocol.dart' as server;
client.VisionPrescriptionLensSpecification visionprescriptionlensspecificationisionPrescriptionLensSpecificationToServer(server.VisionPrescriptionLensSpecification resource) => client.VisionPrescriptionLensSpecification(
id: resource.id == null ? null : resource.id,
extension_: resource.extension_ == null ? null : resource.extension_,
modifierExtension: resource.modifierExtension == null ? null : resource.modifierExtension,
product: resource.product == null ? null : resource.product,
eye: resource.eye == null ? null : resource.eye,
eyeElement: resource.eyeElement == null ? null : resource.eyeElement,
sphere: resource.sphere == null ? null : resource.sphere,
sphereElement: resource.sphereElement == null ? null : resource.sphereElement,
cylinder: resource.cylinder == null ? null : resource.cylinder,
cylinderElement: resource.cylinderElement == null ? null : resource.cylinderElement,
axis: resource.axis == null ? null : resource.axis,
axisElement: resource.axisElement == null ? null : resource.axisElement,
prism: resource.prism == null ? null : resource.prism,
add: resource.add == null ? null : resource.add,
addElement: resource.addElement == null ? null : resource.addElement,
power: resource.power == null ? null : resource.power,
powerElement: resource.powerElement == null ? null : resource.powerElement,
backCurve: resource.backCurve == null ? null : resource.backCurve,
backCurveElement: resource.backCurveElement == null ? null : resource.backCurveElement,
diameter: resource.diameter == null ? null : resource.diameter,
diameterElement: resource.diameterElement == null ? null : resource.diameterElement,
duration: resource.duration == null ? null : resource.duration,
color: resource.color == null ? null : resource.color,
colorElement: resource.colorElement == null ? null : resource.colorElement,
brand: resource.brand == null ? null : resource.brand,
brandElement: resource.brandElement == null ? null : resource.brandElement,
note: resource.note == null ? null : resource.note,

);
