type: server

client_package_path: ../fhirpod_client

extraClasses:
  - package:fhir/r5.dart:Account
  - package:fhir/r5.dart:ActivityDefinition
  - package:fhir/r5.dart:ActorDefinition
  - package:fhir/r5.dart:AdministrableProductDefinition
  - package:fhir/r5.dart:AdverseEvent
  - package:fhir/r5.dart:AllergyIntolerance
  - package:fhir/r5.dart:Appointment
  - package:fhir/r5.dart:AppointmentResponse
  - package:fhir/r5.dart:ArtifactAssessment
  - package:fhir/r5.dart:AuditEvent
  - package:fhir/r5.dart:Basic
  - package:fhir/r5.dart:Binary
  - package:fhir/r5.dart:BiologicallyDerivedProduct
  - package:fhir/r5.dart:BiologicallyDerivedProductDispense
  - package:fhir/r5.dart:BodyStructure
  - package:fhir/r5.dart:Bundle
  - package:fhir/r5.dart:CapabilityStatement
  - package:fhir/r5.dart:CarePlan
  - package:fhir/r5.dart:CareTeam
  - package:fhir/r5.dart:ChargeItem
  - package:fhir/r5.dart:ChargeItemDefinition
  - package:fhir/r5.dart:Citation
  - package:fhir/r5.dart:Claim
  - package:fhir/r5.dart:ClaimResponse
  - package:fhir/r5.dart:ClinicalImpression
  - package:fhir/r5.dart:ClinicalUseDefinition
  - package:fhir/r5.dart:CodeSystem
  - package:fhir/r5.dart:Communication
  - package:fhir/r5.dart:CommunicationRequest
  - package:fhir/r5.dart:CompartmentDefinition
  - package:fhir/r5.dart:Composition
  - package:fhir/r5.dart:ConceptMap
  - package:fhir/r5.dart:Condition
  - package:fhir/r5.dart:ConditionDefinition
  - package:fhir/r5.dart:Consent
  - package:fhir/r5.dart:Contract
  - package:fhir/r5.dart:Coverage
  - package:fhir/r5.dart:CoverageEligibilityRequest
  - package:fhir/r5.dart:CoverageEligibilityResponse
  - package:fhir/r5.dart:DetectedIssue
  - package:fhir/r5.dart:Device
  - package:fhir/r5.dart:DeviceAssociation
  - package:fhir/r5.dart:DeviceDefinition
  - package:fhir/r5.dart:DeviceDispense
  - package:fhir/r5.dart:DeviceMetric
  - package:fhir/r5.dart:DeviceRequest
  - package:fhir/r5.dart:DeviceUsage
  - package:fhir/r5.dart:DiagnosticReport
  - package:fhir/r5.dart:DocumentReference
  - package:fhir/r5.dart:Encounter
  - package:fhir/r5.dart:EncounterHistory
  - package:fhir/r5.dart:Endpoint
  - package:fhir/r5.dart:FhirEndpoint
  - package:fhir/r5.dart:EnrollmentRequest
  - package:fhir/r5.dart:EnrollmentResponse
  - package:fhir/r5.dart:EpisodeOfCare
  - package:fhir/r5.dart:EventDefinition
  - package:fhir/r5.dart:Evidence
  - package:fhir/r5.dart:EvidenceReport
  - package:fhir/r5.dart:EvidenceVariable
  - package:fhir/r5.dart:ExampleScenario
  - package:fhir/r5.dart:ExplanationOfBenefit
  - package:fhir/r5.dart:FamilyMemberHistory
  - package:fhir/r5.dart:Flag
  - package:fhir/r5.dart:FormularyItem
  - package:fhir/r5.dart:GenomicStudy
  - package:fhir/r5.dart:Goal
  - package:fhir/r5.dart:GraphDefinition
  - package:fhir/r5.dart:Group
  - package:fhir/r5.dart:GuidanceResponse
  - package:fhir/r5.dart:HealthcareService
  - package:fhir/r5.dart:ImagingSelection
  - package:fhir/r5.dart:ImagingStudy
  - package:fhir/r5.dart:Immunization
  - package:fhir/r5.dart:ImmunizationEvaluation
  - package:fhir/r5.dart:ImmunizationRecommendation
  - package:fhir/r5.dart:ImplementationGuide
  - package:fhir/r5.dart:Ingredient
  - package:fhir/r5.dart:InsurancePlan
  - package:fhir/r5.dart:InventoryItem
  - package:fhir/r5.dart:InventoryReport
  - package:fhir/r5.dart:Invoice
  - package:fhir/r5.dart:Library
  - package:fhir/r5.dart:Linkage
  - package:fhir/r5.dart:List
  - package:fhir/r5.dart:FhirList
  - package:fhir/r5.dart:Location
  - package:fhir/r5.dart:ManufacturedItemDefinition
  - package:fhir/r5.dart:Measure
  - package:fhir/r5.dart:MeasureReport
  - package:fhir/r5.dart:Medication
  - package:fhir/r5.dart:MedicationAdministration
  - package:fhir/r5.dart:MedicationDispense
  - package:fhir/r5.dart:MedicationKnowledge
  - package:fhir/r5.dart:MedicationRequest
  - package:fhir/r5.dart:MedicationStatement
  - package:fhir/r5.dart:MedicinalProductDefinition
  - package:fhir/r5.dart:MessageDefinition
  - package:fhir/r5.dart:MessageHeader
  - package:fhir/r5.dart:MolecularSequence
  - package:fhir/r5.dart:NamingSystem
  - package:fhir/r5.dart:NutritionIntake
  - package:fhir/r5.dart:NutritionOrder
  - package:fhir/r5.dart:NutritionProduct
  - package:fhir/r5.dart:Observation
  - package:fhir/r5.dart:ObservationDefinition
  - package:fhir/r5.dart:OperationDefinition
  - package:fhir/r5.dart:OperationOutcome
  - package:fhir/r5.dart:Organization
  - package:fhir/r5.dart:OrganizationAffiliation
  - package:fhir/r5.dart:PackagedProductDefinition
  - package:fhir/r5.dart:Parameters
  - package:fhir/r5.dart:Patient
  - package:fhir/r5.dart:PaymentNotice
  - package:fhir/r5.dart:PaymentReconciliation
  - package:fhir/r5.dart:Permission
  - package:fhir/r5.dart:Person
  - package:fhir/r5.dart:PlanDefinition
  - package:fhir/r5.dart:Practitioner
  - package:fhir/r5.dart:PractitionerRole
  - package:fhir/r5.dart:Procedure
  - package:fhir/r5.dart:Provenance
  - package:fhir/r5.dart:Questionnaire
  - package:fhir/r5.dart:QuestionnaireResponse
  - package:fhir/r5.dart:RegulatedAuthorization
  - package:fhir/r5.dart:RelatedPerson
  - package:fhir/r5.dart:RequestOrchestration
  - package:fhir/r5.dart:Requirements
  - package:fhir/r5.dart:ResearchStudy
  - package:fhir/r5.dart:ResearchSubject
  - package:fhir/r5.dart:RiskAssessment
  - package:fhir/r5.dart:Schedule
  - package:fhir/r5.dart:SearchParameter
  - package:fhir/r5.dart:ServiceRequest
  - package:fhir/r5.dart:Slot
  - package:fhir/r5.dart:Specimen
  - package:fhir/r5.dart:SpecimenDefinition
  - package:fhir/r5.dart:StructureDefinition
  - package:fhir/r5.dart:StructureMap
  - package:fhir/r5.dart:Subscription
  - package:fhir/r5.dart:SubscriptionStatus
  - package:fhir/r5.dart:SubscriptionTopic
  - package:fhir/r5.dart:Substance
  - package:fhir/r5.dart:SubstanceDefinition
  - package:fhir/r5.dart:SubstanceNucleicAcid
  - package:fhir/r5.dart:SubstancePolymer
  - package:fhir/r5.dart:SubstanceProtein
  - package:fhir/r5.dart:SubstanceReferenceInformation
  - package:fhir/r5.dart:SubstanceSourceMaterial
  - package:fhir/r5.dart:SupplyDelivery
  - package:fhir/r5.dart:SupplyRequest
  - package:fhir/r5.dart:Task
  - package:fhir/r5.dart:TerminologyCapabilities
  - package:fhir/r5.dart:TestPlan
  - package:fhir/r5.dart:TestReport
  - package:fhir/r5.dart:TestScript
  - package:fhir/r5.dart:Transport
  - package:fhir/r5.dart:ValueSet
  - package:fhir/r5.dart:VerificationResult
  - package:fhir/r5.dart:VisionPrescription
